apiVersion: apps/v1
kind: Deployment
metadata:
  name: sportnite
  labels:
    app: sportnite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sportnite
  template:
    metadata:
      labels:
        app: sportnite
    spec:
      containers:
        - name: api
          image: ghcr.io/sportnite/sportniteserver:vc141b1e091d9b30478deb7e54346b152bf01ae7b
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sportnite
  labels:
    app: sportnite
spec:
  selector:
    app: sportnite
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sportnite
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: projektinzynieria.bieszczadywysokie.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sportnite
            port:
              number: 80