# Kubernetes deployment definition, with single replica
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sportnite
  labels:
    app: sportnite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sportnite
  template:
    metadata:
      labels:
        app: sportnite
    spec:
      containers:
        - name: api
          image: ghcr.io/sportnite/sportniteserver:vae8c899928d9bd9e15e17b7f8796d284d051afb3
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_CONNECTION
              valueFrom:
                # Secret containing the MySQL connection string (MySQL standalone instance)
                secretKeyRef:
                  name: sportnite-secret
                  key: mysql_connection
---
# Service for internal cluster communication
apiVersion: v1
kind: Service
metadata:
  name: sportnite
  labels:
    app: sportnite
spec:
  selector:
    app: sportnite
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
# Ingress exposing server to the internet via nginx-ingress and domain name
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sportnite
spec:
  rules:
    - host: projektinzynieria.bieszczadywysokie.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sportnite
                port:
                  number: 80